In [2]:
import numpy as np

a1 = np.array([1,2,3,4])
print(f"1D Array : {a1}")

a2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(f"2D Array : {a2}")

1D Array : [1 2 3 4]
2D Array : [[1 2 3]
 [4 5 6]]


In [3]:
a3 = np.array([5,6,7,8])

print(f"{a1} + {a3} = {a1 + a3}")

[1 2 3 4] + [5 6 7 8] = [ 6  8 10 12]


In [4]:
a4 = np.arange(10)
print(f"Array with arange : {a4}")

Array with arange : [0 1 2 3 4 5 6 7 8 9]


In [7]:
a4.shape

(10,)

In [8]:
a4[:4]

array([0, 1, 2, 3])

In [9]:
print(a4.reshape(2,5))


[[0 1 2 3 4]
 [5 6 7 8 9]]
